### ISSUE TITLE
rootNodes Bug

### ISSUE THREAD

**Issue by markocupic** [codefog/contao-news_categories#137] opened 2018-03-01 13:04 UTC
If you restrict categories in a newsarchive, the categories want be listed (correctly) in the picker modal window in the edit mode of tl_news.
See here: 
https://drive.google.com/file/d/10UrQZac0jp3y3_pcJrh0lj6tfIxtJus2/view

**Comment by qzminski** [comment] 2018-03-05 15:05
I am not able to reproduce the problem. Sure you are on the latest version? Can you show me the news category tree? Maybe you forgot to select the parent category.

**Comment by markocupic** [comment] 2018-03-07 09:45
Hi Kamil
Thank you for the reply. 
I've made a new screencast. 
https://drive.google.com/file/d/1BvB38z6RVJfbRIR5vKm6_euvGPiTDKy6/view
I've found out, that the categories appear in the modal picker, if I activate a filter. If there is no filter set, Contao will not list any categories.
Can you reproduce that?

Greetings Marko

**Comment by fritzmg** [comment] 2018-03-07 09:47
Did you accidentally close the issue? ;)

**Comment by markocupic** [comment] 2018-03-07 09:47
yes ;-)

**Comment by markocupic** [comment] 2018-03-07 09:54
Where should I select the parent category?

**Comment by qzminski** [comment] 2018-03-13 15:30
Hmm I tried a couple of times but can't reproduce this. Please try one last thing: go to your backend user profile (top right corner) and purge the `Session data` in the `Clear cache` section. If that does not help, you could send me your database dump in a private e-mail message.

**Comment by markocupic** [comment] 2018-03-17 10:47
Hi Kamil
Clearing the session cache does not solve the problem.
I've set up a new contao installation. Now your extension works. ¨
It seems, that there is problem with a 3rd party extension I have installed.
....

**Comment by asaage** [comment] 2018-03-20 02:09
Unfortunately i'm experiencing the same problem.
purgeing the session data, clearing the cache - even using the app_dev route did not help.

After shuffeling around in the categories-hierarcy and checking all categories as valid for a particular archive i managed to get some categories appearing twice and some just wont show up.
please reopen this ticket.

**Comment by qzminski** [comment] 2018-03-20 09:00
@asaage do you have any third party extensions installed on that system?

**Comment by asaage** [comment] 2018-03-20 21:24
- codefog/contao-news_categories
- delahaye/dlh_googlemaps
- inspiredminds/contao-sibling-navigation
- terminal42/contao-changelanguage
- terminal42/dc_multilingual
- terminal42/notification_center

**Comment by qzminski** [comment] 2018-03-21 12:18
@asaage do you mind sending me your mysql dump so I can try to reproduce the issue? Or maybe you have this system online and can provide me the access to it?

**Comment by qzminski** [comment] 2018-03-23 14:15
I have discovered that the double records are coming from the code introduced in https://github.com/contao/core-bundle/pull/1001, as the `$this->root` and `$attributes['rootNodes']` in `DC_Table` are different. As I am unable to fully investigate that complex code, my attempt to fix this is in 59ad1b1.

**Closed** 2018-03-23 15:34 UTC
Labels: bug

**Comment by asaage** [comment] 2018-03-27 14:44
occasionally i still get double entries 🤔 but it's realy hard to reproduce.
