### ISSUE TITLE
News Categories List: Subcategories appear although they shouldn't be there

### ISSUE THREAD

**Issue by jankout** [codefog/contao-news_categories#172] opened 2020-04-16 08:29 UTC
I set in my _**News Categories List**_ module that the subcategories shouldn't appear - even if I choose only the categories that should appear it doesn't work. I guess this is an issue. See the video.
![News categories_error](https://user-images.githubusercontent.com/3715050/79445231-9a828880-7fdc-11ea-9df4-fbf15d38df94.gif)

**Comment by coffeincode** [comment] 2020-04-21 15:24
I am having the same issue.

**Comment by qzminski** [comment] 2020-05-04 16:58
Actually it's not a bug as this module always render the whole tree. Until I come up with a clever solution, for now I would suggest that you use a custom `nav_*` template that does not display subcategories.

The "Include the subcategories" checkbox is in fact used only to calculate the news categories usage – the actual number of news assigned to each category.

**Comment by qzminski** [comment] 2020-05-06 14:09
I have added the "Stop level" field in 3.2.0 which works exactly the same as the one in navigation module.

**Closed** 2020-05-06 14:09 UTC
Labels: enhancement
