### ISSUE TITLE
ModuleNewsMenu -> year GET Parameter is added over and over again

### ISSUE THREAD

**Issue by Defcon0** [codefog/contao-news_categories#120] opened 2017-11-23 09:01 UTC
When using the yearly news menu, the url generated for the links isn't checked for a 'year' parameter already in place. So the change would be (ModuleNewsMenu -> Line 78):

`$arrItems[$intYear]['href'] = $strUrl . ($GLOBALS['TL_CONFIG']['disableAlias'] ? '&amp;' : '?') . 'year=' . $intDate;`

to:

```
use Haste\Util\Url;

// ...

$arrItems[$intYear]['href'] = Url::removeQueryString(['year'], $strUrl) . ($GLOBALS['TL_CONFIG']['disableAlias'] ? '&amp;' : '?') . 'year=' . $intDate;
```

Of course you can also do this without the haste module.

**Comment by qzminski** [comment] 2017-11-25 12:01
Are you using the latest 2.8.6 version of the extension? I am unable to reproduce the issue.

The URL is generated here and in theory it should not contain any query parameters: https://github.com/codefog/contao-news_categories/blob/master/modules/ModuleNewsMenu.php#L238

**Comment by Defcon0** [comment] 2017-11-27 14:00
I have 2.8.5 installed.

**Comment by qzminski** [comment] 2017-11-28 14:52
Must be a duplicate of #113 then.

**Closed by qzminski** 2017-11-28 14:52 UTC
Labels: bug, question
