### ISSUE TITLE
Auswahl der Kategorien ist nach Contao Update nicht mehr möglich

### ISSUE THREAD

**Issue by TS16V** [codefog/contao-news_categories#203] opened 2021-12-13 19:13 UTC
Nach Contao Update auf 4.12.4 ist die Auswahl der Kategorien bei Nachrichten nicht mehr möglich.

**Comment by planepix** [comment] 2021-12-13 21:59
Have this issue also in 4.9.23.

**Comment by qzminski** [comment] 2021-12-14 09:45
Hmm I am not able to reproduce this issue… are you trying to access the categories as a regular backend user, or as an administrator? Have you got DC_Multilingual installed?

**Comment by TS16V** [comment] 2021-12-14 10:03
are you trying to access the categories as a regular backend user, or as an administrator? 


 

Yes, I`m administrtor and backend user

 

 

Have you got DC_Multilingual installed?

 

No, I have not install DC_Multilingual

 

 

More Info to the problem you can find here:

https://community.contao.org/de/showthread.php?82165-Auswahl-der-Kategorien-bei-den-Nachrichten-funktioniert-nicht-mehr&p=552420

 

Bye Thomas

 

 


Gesendet: Dienstag, 14. Dezember 2021 um 10:46 Uhr
Von: "Kamil Kuzminski" ***@***.***>
An: "codefog/contao-news_categories" ***@***.***>
Cc: "TS16V" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [codefog/contao-news_categories] Auswahl der Kategorien ist nach Contao Update nicht mehr möglich (Issue #203)


 

Hmm I am not able to reproduce this issue… are you trying to access the categories as a regular backend user, or as an administrator? Have you got DC_Multilingual installed?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by qzminski** [comment] 2021-12-14 10:10
@TS16V @planepix any chance you could give me an access to the affected system, e.g., via Slack or e-mail?

**Comment by fritzmg** [comment] 2021-12-14 10:29
> More Info to the problem you can find here: https://community.contao.org/de/showthread.php?82165-Auswahl-der-Kategorien-bei-den-Nachrichten-funktioniert-nicht-mehr&p=552420

There isn't really more information there - also it's in German, not English ;)

**Comment by planepix** [comment] 2021-12-14 10:36
Kamil, thank you for your replies. I send you an email.

**Comment by qzminski** [comment] 2021-12-14 11:04
Fixed in 3.4.14.

**Closed** 2021-12-14 11:03 UTC
Labels: bug

**Comment by planepix** [comment] 2021-12-14 11:13
Thank you for fixing this Kamil (y)

**Comment by TS16V** [comment] 2021-12-14 13:17
Thanks for solving the problem
