### ISSUE TITLE
Multi editing and adding news categories - wrong view

### ISSUE THREAD

**Issue by jankout** [codefog/contao-news_categories#132] opened 2018-01-17 11:15 UTC
When I try to add a news category I can see in the lightbox some categories double. In the multi editing view I can choose only one category. 
![news-categories - wrong view](https://user-images.githubusercontent.com/3715050/35040036-0c8a58ec-fb80-11e7-8b3a-52b3c304120f.gif)

**Comment by aschempp** [comment] 2018-01-17 15:06
Possibly an issue with the root node configuration?

**Comment by qzminski** [comment] 2018-01-17 16:55
> In the multi editing view I can choose only one category.

That should be fixed in 96bc119. I am not able to reproduce the second issue though.

**Comment by jankout** [comment] 2018-01-18 13:13
I'm using the latest 4.4.x version.

**Comment by qzminski** [comment] 2018-03-23 14:08
Closing this one, the second issue (with duplicate records) is handled in #137.

**Closed by qzminski** 2018-03-23 14:08 UTC
Labels: bug, question
